---
title: "Regina H Reynolds's CV"
author: Regina H Reynolds
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['css/dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(here)
library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = stringr::str_c(here::here("raw_data"), "/"),  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r, eval = F}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at https://rhreynolds.github.io/cv")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://raw.githubusercontent.com/RHReynolds/cv/main/docs/rhr_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Programming languages {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R packages [datadrivencv](https://github.com/nstrayer/datadrivencv) and  [pagedown](https://github.com/rstudio/pagedown). 

The source code is available [GitHub](https://github.com/RHReynolds/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Regina H Reynolds {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Work experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('work_experience', resume = TRUE)
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education', resume = FALSE)

print_breaks(
  html_breaks = 0,
  pdf_breaks = 1,
  pdf_mode = params$pdf_mode
  )
```


Teaching experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching_positions', resume = TRUE)
```


Voluntary Work {data-icon=hands-helping}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('voluntary_work', resume = TRUE)

```


Key publications {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('publications_aside')
```
:::

```{r}
CV %<>% print_section('selected_publications')
```


Conferences {data-icon=comments}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('conferences')
```


```{r}
CV %<>% print_links()
```

