---
title: "Regina H Reynolds's Resume"
author: Regina H Reynolds
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['css/dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "C:/Users/rhrey/OneDrive/Personal/Jobs & CVs/Latest CV/cv/raw_data/",  
  pdf_mode = params$pdf_mode
)

# Filter for data to be included in resume
CV$entries_data <- 
  CV$entries_data %>% 
  dplyr::filter(in_resume == TRUE)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r, eval = F}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this resume online with links at _https://rhreynolds.github.io/cv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download as a PDF](https://github.com/RHReynolds/cv/blob/main/docs/rhr_resume.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Programming languages {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

The long-form version of my CV, with a list of publications, conferences attended and voluntary work is available [here](https://rhreynolds.github.io/cv/cv.html). 

Made with the R packages [datadrivencv](https://github.com/nstrayer/datadrivencv) and  [pagedown](https://github.com/rstudio/pagedown). 

The source code is available [GitHub](https://github.com/RHReynolds/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Regina H Reynolds {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

Work experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('work_experience')
```

Teaching experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching_positions')
```